export const links = [
  { path: "/humor", label: "유머" },
  { path: "/free", label: "자유" },
];

export const contants = [
  { num: 1, title: "test1", writer: "unknown1" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },

  { num: 2, title: "test2", writer: "unknown2" },

  { num: 2, title: "test2", writer: "unknown2" },

  { num: 2, title: "test2", writer: "unknown2" },

  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
  { num: 2, title: "test2", writer: "unknown2" },
];
